---
database:
  host: database
  port: "5432"
  database: desafio
  username: admin
  password: UE9TVEdSRVNfUEFTU1dPUkQK
webserver:
  port: "8443"
  ssl_enabled: "false"
  name: "api"
  host: "0.0.0.0"
  version: ""
cache:
  port: "6379"
  host: "redis"
  password: "cmVkaXMtc2VydmVyCg"
  database: 0
graphql:
  port: "8080"
